### PR TITLE
A couple minor fixes

### PR DESCRIPTION
**Pull request by yujiberra**
This PR makes two minor changes:

- Prevent the login modal from being dismissed by clicking outside of it or pressing escape 33d1ec75e8b82547fa9e93165ea37c897a4c3300
- Delete some unnecessary code

I checked the following:
- login modal behaves as expected
- batch deletion and batch upload still function, and the sample attributes &expression data from a newly created batch can be viewed as expected

### CODE REVIEW

**Comment by jtnystrom** [comment]
I was going to review this, could you resolve the conflict with master? Thanks

**Comment by yujiberra** [comment]
@jtnystrom 
Sorry to keep you waiting, conflict is resolved!

**Review by jtnystrom — APPROVED** [review]
Thanks, I tested this and everything looks fine, confirmed that the modal dialog can no longer be clicked away. LGTM.

**Comment by yujiberra** [comment]
Thanks for the review!

**Pull request merged**
