### PR TITLE
Self-service registration and access control

### PR DESCRIPTION
**Pull request by yujiberra**
This PR makes code changes to integrate with FusionAuth self-service registration, which allows a user to create an account (rather than an admin user needing to do so). It also updates the PostgreSQL initialization SQL file to set up self-service registration in FusionAuth.

In addition, this PR begins implementing access control based on a paradigm where in order to view data from e.g. the adjuvant dataset, the user will need to have the `adjuvant` role in FusionAuth. The `otg` role is set as a default role, so that users who create an account with self-service registration will have access to it.
 
The main code changes are as follows:
- Users are now required to log in in order to use the viewer (not just admin functionality)
- If not logged in, the user is shown a modal dialog giving them a choice between logging in and registering
- When fetching batches for a dataset with the `/batch/dataset/{datasetId}` endpoint, the user is required to have the `datasetId` role
  - Similar changes will need to be made to various other endpoints (e.g., the ones for fetching samples for a given batch, or for fetching expression data for sample groups)

The changes made to the initial data for the FusionAuth docker data are as follows:
- Enable self-service registration, requiring email, full name, and password (entered twice)
- Add the following roles: `otg`, `adjuvant`, `adju-mirna`
- Give all the roles to the admin account
- Add a non-admin account with only the `otg` role (email address `pubbawup@gmail.com`, password `toxygates`)
- Add the base URL of the application as an authorized redirect URL 
  - This is actually unnecessary so I should remove it at sometime, but making these dumps is a bit time-consuming so I'll remove it next time I commit a change to the SQL

Some additional minor code changes include the following:
- Only show the link to the admin screen if the user has the admin role
- A logged-in non-admin user who tries to access the admin screen (by e.g. entering a URL) is redirected to the viewer screen
- No data is fetched if the user is logged in

There is an issue where if you choose a dataset like adjuvant in the Sample Broser, and then log out and log in with a user who doesn't have access to the dataset, the batches won't load, even after you switch the dataset to otg. But I'd like to postpone dealing with this since it's an edge case, it's fixed by reloading after picking a dataset the user has access to, and this PR is getting quite big already.

I tested the following while running with fresh FusionAuth/Postgres containers:
- Opening the app without being logged in causes the login modal to appear, and no data to be fetched
- Logging in from the modal redirects the user back to the application in a logged in state
- Registering from the modal redirects the user back to the application in a logged in state
- Admin link is shown only to admin users
- Navigating to /admin as non-admin redirects to viewer
- Users can only list batches for a dataset with the /batch/dataset/:dataset endpoint if they have the appropriate role

### CODE REVIEW

**Comment by jtnystrom** [comment]
A note in case we need it in the future: if the docker containers already have their volumes created on the system, they might not update automatically just because this branch is merged (i.e. init.sql changes). The volumes can be forcibly removed by doing `docker-compose down -v`, and then the next `docker-compose up` will recreate them.

**Comment by jtnystrom** [comment]
> * Admin link is shown only to users

I guess this means "only to admin users".

I tested all the cases you tested, and they seem to work fine for me too. LGTM. I will add appropriate role checking to the various API calls, following your example.

**Review by jtnystrom — APPROVED** [review]

**Comment by jtnystrom** [comment]
> There is an issue where if you choose a dataset like adjuvant in the Sample Broser, and then log out and log in with a user who doesn't have access to the dataset, the batches won't load, even after you switch the dataset to otg. But I'd like to postpone dealing with this since it's an edge case, it's fixed by reloading after picking a dataset the user has access to, and this PR is getting quite big already.

I'd like to make it so that we only return those datasets that the user has access to in get("/dataset"), maybe that would solve the issue by itself?

**Comment by yujiberra** [comment]
@jtnystrom 
Thanks for the review and for the comment about docker!

> I guess this means "only to admin users".

Yup that's right, I'll fix that.

> I'd like to make it so that we only return those datasets that the user has access to in get("/dataset"), maybe that would solve the issue by itself?

That is how I was hoping `get("/dataset")` would work in the future, and that would help, but I think I might need to do some frontend work too, because we store the chosen datasets, batches etc. in local storage.

**Pull request merged**
