### PR TITLE
Add docker-compose with out-of-the-box FusionAuth configuration

### PR DESCRIPTION
**Pull request by yujiberra**
This PR adds a docker-compose configuration that sets up Docker images running FusionAuth and PostgreSQL (as required by FusionAuth), pre-configured with tenant info, security keys, etc. for Panomicon.

That mainly happens in f2c16d3c0b603deb3f5a7d63762ad211812fea0b:
- `docker-compose.yml` configures the FusionAuth and PostgreSQL docker images
- `init.sql` is a SQL dump that initializes the PostgreSQL database; it's run when docker-compose first creates the images based on `docker-compose.yml`
- `.env` sets default environment variable values for the Docker images

If you have docker installed, just running `docker-compose up` in the directory with `docker-compose.yml` will start up the images, initializing them the first around.

In the above configuration the only FusionAuth account has email `yuji.kosugi@gmail.com` and password `panomicon`.

(764abc1b22a6a4737f243a647befc51f4a96d851 upgrades the fusionauth-java-client dependency to one that is compatible with the latest version of fusionauth)

I also add an `.envrc.example` file (4400741cd3118a9337203a3a05845ab7075ba74a). .envrc files are used with [direnv](https://direnv.net/), a useful utility that lets you automatically load values for environment variables when you `cd` into a directory. I added this mainly to add environment variables to configure the backend to work with the FusionAuth deployment set up by docker-compose, but I also include the other environment varables I set in my .envrc file. You'll need to change various paths before you can use the file yourself, but once you do it should cover all the environment variables you need.

Speaking of which, we should update README.md someday since it's out of date but 
- I'd prefer not to be the one to do so because once I start it'll be hard for me to stop (it needs a lot of work imo)
- Might make sense to wait until after I add Fuseki to the docker-compose file

**Tests**
I made sure that after initializing and staring up the docker images and starting up Scalatra using the `.envrc.example` file as my actual `.envrc` I was able to log into and log out of Admin mode in the front end.

### CODE REVIEW

**Comment by RodolfoAllendes** [comment]
Just one quick suggestion...
the .envrc example is really usefull when setting up your own environment, but I also have a personalized one on my folder (which is not commited because it was part of the .gitignore file)...  so, probably you can just keep it with a different name? something along the line of `.envrc_sample` ???

everything else looks ok to me :)

**Comment by yujiberra** [comment]
@RodolfoAllendes 
Hey thanks, I think I did call it `.envrc.example` though? I guess it's slightly confusing in the PR text so I'll revise that.

**Comment by yujiberra** [comment]
@jtnystrom 
Hey, I know you started testing this PR, but if you've finished could you please approve it?

**Review by jtnystrom — APPROVED** [review]
Hi, thanks for your work. I tested this and it seems to work well (can start with docker-compose, can run scalatra and the angular app while authenticating with fusionauth from these docker images). This is really nice to have and should be a good foundation as we dockerize more things. I may have more feedback and comments when we get to that stage, but for now, LGTM.

**Comment by yujiberra** [comment]
@jtnystrom 
Thanks! I'll merge this then.

>This is really nice to have and should be a good foundation as we dockerize more things. I may have more feedback and comments when we get to that stage

Sounds good; if we get to a point where we want to use Docker for deployment I think we'll probably want to use separate docker-compose files but we can discuss in the future as you said.

**Pull request merged**
