### PR TITLE
Lint and prettify angular files on commit

### PR DESCRIPTION
**Pull request by yujiberra**
This PR adds configuration to automatically lint and prettify files for the front end on commit.

The changes are as follows:
- install prettier 4d280714646a6ace1bef08ae26c7efc401bc6811
- install husky, lint-staged, and set them up to run prettier and eslint on commit c86ef7866ac1554cf80f9f17a92467ebe47b0949
- add .eslintcache to .gitignore 12fa99de26afade4f9f809781ea1e541137b3bbf
- apply prettier to all files 7e2df1cb6f1cbd7f2d735ca3617e87b8897ab4de (this is a huge diff)

To test these changes I made some test commits and made sure that:
- prettier formats any files that are changed
- linter errors prevent halt the commit process
- if no linter errors are present, then files can successfully be committed

### CODE REVIEW

**Review by jtnystrom — APPROVED** [review]
This looks like a nice thing to have. You seem to have tested it thoroughly.
I had to run `npm install` to install the linter package.
Then I tried to make a test commit locally with some trivial indentation changes, and the linter did run.
It of course reverted my indentations and then prevented me from making what was then an empty commit.
LGTM.

**Comment by jtnystrom** [comment]
Quick question, what is the mechanism by which git discovers and runs the hook?
Edit: I discovered that husky had installed itself into `.git/config`, presumably something that was done when I ran `npm install`.

**Review by RodolfoAllendes — APPROVED** [review]
I did not review as thoroughly as @jtnystrom, but everything looks fine to me.

thank you for looking into this :)

**Comment by yujiberra** [comment]
Thank you both for reviewing this!

**Pull request merged**
